version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: weather-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root  #Contraseña del usuario "root"
      MYSQL_DATABASE: weatherapp_db #Nombre de la DB
    ports:
      # Expone el puerto de la DB al host para que pueda conectarse con la app
      - "3306:3306"
    volumes:
      # Persiste los datos de la base de datos para que no se pierdan al reiniciar el contenedor
      - db-data:/var/lib/mysql

  app:
    build: .
    container_name: weather-app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      # Configuración de la base de datos para que apunte al contenedor 'db'
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/weatherapp_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root # Debe coincidir con MYSQL_ROOT_PASSWORD
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  db-data:
